### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [martinetd/mooshika#5]
[Extra null pointer checks are not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [a function like “msk_destroy_trans”](https://github.com/martinetd/mooshika/blob/188439e9a6e46f551516915a90c52abed80bd296/src/trans_rdma.c#L1369 "Update candidate").

**Comment by martinetd** [comment]
I'm aware of this and would have written these without the checks now, but "fixing" old code is not a priority - patches welcome.

**Comment by elfring** [comment]
How do you think about to apply a corresponding update suggestion which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle")?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```
