### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [martinetd/mooshika#7]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "Determination of parameters for building software with POSIX threads usage")” to [your build specification](https://github.com/martinetd/mooshika/blob/3bde2d1e1b6c4c1f2e0461c74bb42f5cac35479f/configure.ac#L24 "Update candidate")?

**Comment by martinetd** [comment]
Using `-lpthread` directly like I did at the time isn't portable, but good enough for the intended scope of the library.
I'll take a patch if someone who cares sends one.

**Comment by elfring** [comment]
Can it be nicer to integrate the advice from the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "Determination of parameters for building software with POSIX threads usage")” directly?
